apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pacman-secret
  namespace: default
spec:
  encryptedData:
    pass: AgDUDo/5yiQ13e/m09VoOCzw46Pkwpd61YIoHI5LHUM9HrcSQDt+UtVdjFz5kE7E98MG2Iqht5hl8oV+Sx31pBmQsQPR0xaqrRlg1tEGQImr1LRLg9eddQGDsSdhiOw71gVwkEYwWNyd00Srq01SvCU4edn8XEMPjJIq0g4Ldc60LSerlOJ2at4hoPUVznPBFoiLwGjw7UjjHEgNosb+V9Ki3a8PG3Shji+LbCHAnmzUtCB8P6WUbXiC26LyQodt8N8IuJEy7L1aQRqeuvD+CnyusTWJNZe1Acf7mb8/RR+zwxEZmYeTBLMGDRJvgexlmzIwa9X8GumBiuQcZx010q+cCvOx0aKfds+aRvB3oDhCOMYoQ99p2q1aokNpxSDdboyvFpcWekyHKS9HRhlij1UQs53QNxKvkmrg79VJZkZaoi9i8SJN32AJJVeRAy2F5T2o46b0NirA1I+p59L9p7peMe7YBBtxyWingfAG+0ZAoiqpeznukMrsdIm2rZipwL1rZs/b8OkheQBOJTHAsgtlRZ5wUkTO3LV7v80Rai+Rg7JMrltEMXNFtUXTwLjbQmHph3QiieVPo+/8xaX5y63NJtrGc9WInWt7sRuUO4Hzd/zDcr5grKI8TzwfO6/00zdmrEVw6KlNtwvHJORT3csO9+eSY/sfeYQwSAcpO8f8+2Kr8ko3qST7gW9OQc1Rqpja9ASqLSU=
    user: AgAyEIIaelSxMLkR5HJfUvqCyQAyoiNt0HaUhFY2pNX7hh9zLw8yxIRA4Gca/Ybzv5tfBK+hqTm+BI+BnqRVkoFzXeVpWELy66aQ/dfN4wHxIRMBzo0VTNnt6H8ttgXDlT6bqp9ZrDzbYBSkBiBsYbR/4QjFC5uyMV9a4dNPh75gXoesR60qVa8zlK3spx9zYhGYPjMdxIrQciJ4mE+O8ZYtzds1fvHwWUEMgp7d6hMMUTpXOT81RbOgLKyO0XBImQFqjCbNRRfvGlTNeWiULzY5HpJoUcYXSGnZizSQReCWU/wS1enE8fDiIEyHJP3ZTfZRbIcgMrdE2H4txtea0AQ6pHcqH63vtc5oiug1h3DqVlDXMmk/FPrnMwFKts3hYQE5E1dAp4IyzRUpI3W98olGnVvvdCwLO6mVd+EUOVCPRtgTFyEadZ4MDKRKz9xjUpELmxhFzpJnKs5m+eRbfPfN1AsEC11y6mPl1Yi/840d8X/U0w8er9IAVtDE6DIe0AvUBdyA4kymqZgaxPXMQxJhrz2DxAoFlMXOTIeIx+kqFIR51pS/AMAmZs2lwamNbo8KP3XE+688VaDwVI4vfQdVs/M5XE2LuU88Gbp0dJCkLaBKOUy5+cch9kPbv8sFM0Fpmzn5rphghNL32qCxt8Z/u5J9VhK4UBslz3RnZAG9q/w6pVTDHH2Sg6AmQ2RHiDvhH35Y510=
  template:
    metadata:
      creationTimestamp: null
      name: pacman-secret
      namespace: default
    type: Opaque

